### ISSUE TITLE
bitwise operations

### ISSUE THREAD

**Issue by Hitesh18082001** [aayushi-droid/Edabit-Solutions#351] opened 2020-10-17 05:37 UTC
Before jumping into Pr first comment for assign.

Problem statement :write a program to print the result of bitwise operations(AND,OR,XOR) on the given two numbers.
Probelm Link : https://edabit.com/challenge/qA5aT6XYfafH3NwcX
Choose one Cateorgy - Very Easy, Easy, Medium, Hard, Very Hard, Expert 
question category*:EASY 

---
Before submitting a PR please Check some details.

- [ ] fileName formet should be in camelcase
    example- returnTheNextNumber.py
- [ ]  Choose label for Problem , example- "good first issue", "easy"
- [ ]  In file there should be problem statement and link to problem
```cpp
/* Problem-Task : This program will add two numbers
 * Problem Link : https://edabit.com/challenge/SFzHtm63XT6EYNHWY
*/
int main() {
    int bla;
    return 0;
}
```

This repository is vaild for HacktoberFest2020

Read before making PR - [How to contribute on Github](https://www.dataschool.io/how-to-contribute-on-github/)
Good Luck,

**Comment by Hitesh18082001** [comment] 2020-10-17 05:37
Please assign this issue to me!!
Thanks

**Comment by aayushi-droid** [comment] 2020-10-19 11:03
Duplicate of #320

**Closed as completed by aayushi-droid** 2020-10-19 11:03 UTC
Labels: C++, hacktoberfest
